// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uBj3wrifSizTBF-zzMAj-emEfhma1h8',
    appId: '1:462870207180:android:6420256f426cda24778069',
    messagingSenderId: '462870207180',
    projectId: 'chatapp-e44d9',
    storageBucket: 'chatapp-e44d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Ue-2q0rYXSrzUzoYgUm9Os2FtACHJmw',
    appId: '1:462870207180:ios:8ed52283a16f4d6c778069',
    messagingSenderId: '462870207180',
    projectId: 'chatapp-e44d9',
    storageBucket: 'chatapp-e44d9.appspot.com',
    iosClientId: '462870207180-i5v5g6i5qqgfg1e07i44nt86ths0ft0b.apps.googleusercontent.com',
    iosBundleId: 'com.atwom.ames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5uBj3wrifSizTBF-zzMAj-emEfhma1h8',
    appId: '1:462870207180:android:6420256f426cda24778069',
    messagingSenderId: '462870207180',
    projectId: 'chatapp-e44d9',
  );

}
